name: nameless_audio
description: Local audio player for multi-session ASMR and voice library playback.
publish_to: 'none'
version: 0.9.92+992

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  just_audio: ^0.10.5
  file_picker: ^10.3.10
  permission_handler: ^12.0.1
  path: ^1.9.1
  google_fonts: ^8.0.2
  mime: ^2.0.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.1
  flutter_secure_storage: ^9.2.4
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6
  provider: ^6.1.2
  flutter_riverpod: ^2.6.1
  audio_session: ^0.2.1
  window_manager: ^0.4.3
  ffmpeg_kit_flutter_new_audio: ^2.0.0
  lottie: ^3.3.3
  desktop_multi_window: ^0.3.0
  media_kit: ^1.0.2
  media_kit_libs_windows_audio: ^1.0.9
  flutter_acrylic: ^1.1.4
  flutter_animate: ^4.5.2
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0




flutter:
  uses-material-design: true
  assets:
    - assets/lottie/empty_library.json
