param(
    [string]$AndroidDirectory = (Join-Path $PSScriptRoot '..\android')
)

$ErrorActionPreference = 'Stop'
$androidDirectoryPath = [System.IO.Path]::GetFullPath($AndroidDirectory)
$propertiesPath = Join-Path $androidDirectoryPath 'key.properties'
$keystoreName = 'local-release-keystore.jks'
$keystorePath = Join-Path $androidDirectoryPath $keystoreName

function Find-Keytool {
    $candidates = @(
        $(if ($env:JAVA_HOME) { Join-Path $env:JAVA_HOME 'bin\keytool.exe' }),
        'C:\Program Files\Android\Android Studio\jbr\bin\keytool.exe'
    ) | Where-Object { $_ -and (Test-Path -LiteralPath $_ -PathType Leaf) }
    if (@($candidates).Count -gt 0) { return @($candidates)[0] }

    $command = Get-Command keytool.exe -ErrorAction SilentlyContinue
    if ($command) { return $command.Source }
    throw 'keytool.exe was not found. Install Android Studio or set JAVA_HOME to a JDK.'
}

function New-RandomPassword {
    $bytes = New-Object byte[] 32
    $generator = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $generator.GetBytes($bytes)
    } finally {
        $generator.Dispose()
    }
    return ([BitConverter]::ToString($bytes) -replace '-', '').ToLowerInvariant()
}

if (Test-Path -LiteralPath $propertiesPath -PathType Leaf) {
    $storeFileLine = Get-Content -LiteralPath $propertiesPath |
        Where-Object { $_ -match '^\s*storeFile\s*=' } |
        Select-Object -First 1
    if (-not $storeFileLine) {
        throw "$propertiesPath does not define storeFile."
    }
    $configuredStoreFile = ($storeFileLine -split '=', 2)[1].Trim()
    $configuredStorePath = Join-Path $androidDirectoryPath $configuredStoreFile
    if (-not (Test-Path -LiteralPath $configuredStorePath -PathType Leaf)) {
        throw "Configured release keystore does not exist: $configuredStorePath"
    }
    Write-Host "[OK] Local release signing already configured: $propertiesPath"
    exit 0
}
if (Test-Path -LiteralPath $keystorePath -PathType Leaf) {
    throw "Found $keystorePath without key.properties. Restore the matching key.properties or remove the orphaned keystore intentionally."
}

$keytool = Find-Keytool
$password = New-RandomPassword
$alias = 'nameless-audio-local-release'

Write-Host '[INFO] Creating a persistent local release signing key...'
& $keytool -genkeypair -keystore $keystorePath -storepass $password `
    -keypass $password -alias $alias -keyalg RSA -keysize 4096 -validity 10000 `
    -dname 'CN=Nameless Audio Local Release, OU=Local Development, O=Nameless Audio, C=CN' `
    -noprompt
if ($LASTEXITCODE -ne 0 -or -not (Test-Path -LiteralPath $keystorePath -PathType Leaf)) {
    throw 'keytool failed to create the local release keystore.'
}

@"
# Generated by tool/setup_local_release_signing.ps1.
# Local-only secret. Never commit this file or the matching keystore.
storeFile=$keystoreName
keyAlias=$alias
storePassword=$password
keyPassword=$password
"@ | Set-Content -LiteralPath $propertiesPath -Encoding ascii

Write-Host '[OK] Created persistent local release signing configuration.'
Write-Host '[INFO] Back up key.properties and local-release-keystore.jks together.'
