const Map<String, String> appLanguageJa = {
  'app_title': 'Nameless Audio',
  'permission_group_playback': '再生の基本',
  'permission_group_reliability': 'タイマーと信頼性',
  'permission_group_advanced': '高度な機能',
  'onboarding_title': 'Nameless Audio',
  'onboarding_subtitle': 'ローカル優先のASMR・音声プレーヤーです。',
  'onboarding_local': 'ライブラリと再生状態はこの端末に保存されます。',
  'onboarding_online_optional': 'ASMR.ONEなどのオンライン機能は任意です。',
  'onboarding_permissions': '権限は関連機能を使用するときだけ要求します。',
  'onboarding_start': '始める',
  'privacy_summary_action': 'プライバシー概要を見る',
  'privacy_summary_title': 'プライバシー概要',
  'privacy_summary_local_title': 'ローカル保存が基本',
  'privacy_summary_local_body': 'ライブラリ、設定、再生状態はこの端末に保存されます。',
  'privacy_summary_network_title': '任意のオンライン機能',
  'privacy_summary_network_body': '通信はASMR.ONE、メタデータ、更新などでのみ使用します。',
  'privacy_summary_diagnostics_title': '診断情報はユーザーが管理',
  'privacy_summary_diagnostics_body': '選択して書き出した場合のみ、匿名化した診断情報を作成します。',
  'nav_library': 'ライブラリ',
  'nav_sessions': 'プレイリスト',
  'nav_settings': '設定',
  'timer': 'タイマー',
  'done': '完了',
  'close': '閉じる',
  'open_timer_settings': 'タイマー設定を開く',
  'timer_play_plus': '再生 + {time}',
  'asmr_player': 'NL Audio',
  'music_library': 'ライブラリ',
  'playback_sessions': 'プレイリスト',
  'settings': '設定',
  'video_to_audio': '動画を音声に変換',
  'import_audio': '音声を追加',
  'import_folder': 'フォルダを追加',
  'import_file': 'ファイルを追加',
  'import_library': '曲庫を追加',
  'refresh_watched_folder': '監視フォルダを更新',
  'more_actions': 'その他の操作',
  'fixed_card_positions': 'カード位置を固定',
  'batch_metadata': 'データを一括補完',
  'batch_metadata_hint':
      'ASMR.ONE の作品情報を優先して取得し、失敗した場合は DLsite を使用します。現在の作品を確認すると、次の作品へ進みます。',
  'batch_metadata_no_metadata': 'すべてのデータが不足している作品',
  'batch_metadata_any_missing': '不足データがある作品',
  'batch_metadata_has_rj_code': 'RJ番号が入力済みの作品',
  'batch_metadata_specific': '作品を指定',
  'batch_metadata_picker_search': 'RJ番号やタイトルを検索',
  'batch_metadata_picker_done': '完了 ({count})',
  'batch_metadata_all': 'すべてのデータ',
  'batch_metadata_start': '補完を開始',
  'batch_metadata_progress': '{current} / {total}',
  'batch_metadata_summary': '一括補完の概要',
  'batch_metadata_total': '作品数',
  'batch_metadata_applied': '確認済み',
  'batch_metadata_skipped': 'スキップ済み',
  'batch_metadata_unprocessed': '未処理',
  'batch_metadata_load_failed': 'ローカルライブラリを読み込めませんでした。もう一度お試しください。',
  'library_manage_empty': '追加済みのライブラリはありません。',
  'skip': 'スキップ',
  'search': '検索',
  'search_audio_placeholder': 'オーディオを検索...',
  'scanning_title': 'スキャン中',
  'loading_dot': '読み込み中...',
  'playback_loading': '読み込み中',
  'playback_state_playing': '再生中',
  'playback_state_paused': '一時停止中',
  'playback_failed_retry': '再生に失敗しました。タップして再試行',
  'asmr_playback_load_failed_retry': '読み込みに失敗しました。タップして再試行',
  'asmr_playback_network_failed_retry': 'ネットワーク接続に失敗しました。タップして再試行',
  'scan_cancel': 'スキャンをキャンセル',
  'scan_cancelled': 'スキャンをキャンセルしました。',
  'scan_stage_preparing': 'フォルダーを読み込み中...',
  'scan_stage_enumerating': '音声ファイルを検索中...',
  'scan_stage_merging': '曲情報を読み込み中...',
  'scan_stage_saving': 'ライブラリを保存中...',
  'scan_stage_covers': 'カバーを読み込み中...',
  'scan_processed': '{processed} 件を処理済み',
  'scan_processed_total': '{processed} / {total} 件を処理済み',
  'scan_current_folder': '現在のフォルダ',
  'scan_found': '発見',
  'scan_duplicate': '重複',
  'scan_failure': '失敗',
  'audio_count': '{count} 曲',
  'folder_count': '{count} フォルダ',
  'no_audio_files': '音声ファイルがありません',
  'no_audio_found': '音声ファイルが見つかりませんでした。',
  'no_search_results': '一致する検索結果がありません',
  'search_try_another_term': '別のキーワードを試すか、検索をクリアしてください。',
  'search_match_count': '{match} / {total} 曲一致',
  'import_audio_hint': '下のボタンから音声を追加できます。フォルダ/ファイル両方に対応します。',
  'need_storage_permission_scan_folder': 'フォルダをスキャンするにはストレージ権限が必要です。',
  'need_storage_permission_import_audio': '音声を追加するにはストレージ権限が必要です。',
  'import_audio_failed': '音声を追加できませんでした。再試行してください。',
  'import_failed_next_step': '選択したファイルまたはフォルダにまだアクセスできるか確認してから、もう一度お試しください。',
  'scan_failed_next_step': 'ストレージ権限と元のフォルダがまだ存在するか確認してから、もう一度お試しください。',
  'refresh_done_added': '更新完了：{count} 曲を追加しました。',
  'refresh_done_no_new': '新しい音声は見つかりませんでした。',
  'asmr_refresh_done_updated': 'カテゴリ内容を更新しました。',
  'asmr_online_playback': 'ASMR.ONE オンライン再生',
  'asmr_online_optional_notice': 'ASMR.ONE は任意のオンライン機能で、使用中のみネットワークに接続します。',
  'asmr_collected_count': '\u73fe\u5728 {count} \u4f5c\u54c1\u53ce\u9332',
  'asmr_refresh_no_updates': '新しい更新はありません。',
  'asmr_refresh_failed': '同期に失敗しました。再度引き下げて更新してください。',
  'asmr_favorite_added': 'お気に入りに追加しました。',
  'asmr_favorite_removed': 'お気に入りを解除しました。',
  'asmr_category_sales': '販売数',
  'asmr_category_rating': '評価',
  'asmr_category_reviews': 'レビュー数',
  'asmr_category_release': '発売',
  'asmr_category_collected': '収録',
  'asmr_category_recommendation': 'おすすめ',
  'asmr_category_favorites': 'お気に入り',
  'asmr_category_history': '履歴',
  'asmr_more': 'その他',
  'asmr_account_menu': 'アカウント',
  'asmr_account_title': 'ASMR.ONE アカウント',
  'asmr_login_title': 'ログイン',
  'asmr_login_account': 'アカウント',
  'asmr_login_password': 'パスワード',
  'asmr_login_action': 'ログイン',
  'asmr_logout_action': 'ログアウト',
  'asmr_logged_in_as': 'ログイン中：{name}',
  'asmr_login_success': 'ログインしました。',
  'asmr_logout_success': 'ログアウトしました。',
  'asmr_login_failed': 'ログインに失敗しました。アカウントとパスワードを確認してください。',
  'asmr_token_expired': 'ログインの有効期限が切れました。再ログインしてください。',
  'asmr_account_sync_now': '今すぐ同期',
  'asmr_account_syncing': 'アカウントデータを同期中...',
  'asmr_account_sync_done': 'アカウントデータを同期しました。',
  'asmr_account_sync_failed': 'アカウント同期に失敗しました。あとでもう一度お試しください。',
  'asmr_account_not_synced': 'まだ同期されていません。',
  'asmr_account_last_sync': '前回の同期：{time}',
  'asmr_account_pending_count': '{count} 件の変更が同期待ちです',
  'asmr_categories_title': '分類',
  'asmr_language_title': '言語',
  'follow_page_language': 'ページ言語に従う',
  'asmr_language_zh': '中国語',
  'asmr_language_ja': '日本語',
  'asmr_language_en': '英語',
  'asmr_search_hint': '作品を検索...',
  'asmr_empty_category': 'このカテゴリにはまだ内容がありません。',
  'asmr_load_more_hint': 'さらに読み込むには上へスワイプ',
  'asmr_add_to_playlist': 'プレイリストに追加',
  'asmr_added_to_playlist': 'プレイリストに追加しました：{title}',
  'asmr_detail_action': '詳細情報',
  'asmr_detail_tooltip': '作品の詳細情報を表示',
  'asmr_favorite_action': 'お気に入り',
  'asmr_unfavorite_action': 'お気に入り解除',
  'asmr_add_favorite_tooltip': 'お気に入りに追加',
  'asmr_download_action': 'ダウンロード',
  'asmr_download_work_tooltip': '作品をダウンロード',
  'asmr_empty_track_tree': 'この作品には展開できる音声ツリーがありません。',
  'asmr_circle_label': 'サークル',
  'asmr_tags_label': 'タグ',
  'asmr_detail_title': '詳細情報',
  'asmr_detail_readonly_hint': '読み取り専用モードです。編集やドラッグ並べ替えはできません。',
  'asmr_detail_load_failed': '作品情報の読み込みに失敗しました。しばらくしてから再試行してください。',
  'asmr_detail_basic_info': '基本情報',
  'asmr_detail_other': 'その他',
  'asmr_detail_statistics': '統計情報',
  'asmr_detail_release_date': '発売日',
  'asmr_detail_duration': '長さ',
  'asmr_detail_sales': '販売数',
  'asmr_detail_rating': '評価',
  'asmr_detail_unrated': '未評価',
  'asmr_detail_reviews': 'レビュー数',
  'asmr_detail_age_rating': '年齢区分',
  'asmr_detail_language_editions': '言語版',
  'asmr_detail_description': '紹介',
  'asmr_unknown_circle': '不明なサークル',
  'asmr_missing_rj': 'RJ番号なし',
  'asmr_has_subtitle': '字幕あり',
  'asmr_unknown': '不明',
  'asmr_download_title': 'ダウンロード',
  'asmr_download_choose_path': '保存先を選択',
  'asmr_download_change_path': '保存先を変更',
  'asmr_download_path_missing': '保存済みのダウンロード先が見つかりません。保存先を選び直してください。',
  'asmr_download_conflict_title': '同名項目の処理',
  'asmr_download_conflict_message': '保存先に同名のファイルやフォルダがある場合、どう処理しますか？',
  'asmr_download_conflict_skip': 'スキップ',
  'asmr_download_conflict_overwrite': '上書き',
  'asmr_download_task_running': '現在実行中のダウンロードタスクがあります',
  'asmr_download_select_required': 'ダウンロードするファイルまたはフォルダを先に選択してください',
  'asmr_download_completed_with_failures': 'ダウンロードは完了しましたが、一部のファイルに失敗しました',
  'asmr_download_failed': 'ダウンロードに失敗しました：{error}',
  'asmr_download_failed_title': 'ダウンロードに失敗しました',
  'asmr_download_failed_next_step': '保存先フォルダとネットワーク接続を確認してから、もう一度お試しください。',
  'asmr_download_starting': 'ダウンロード中',
  'asmr_download_confirm': 'ダウンロードを開始',
  'asmr_download_added_to_list': 'ダウンロードリストに追加しました',
  'asmr_download_task_title': 'ダウンロードタスク',
  'asmr_download_cancel_and_clear': 'ダウンロードをキャンセルして取得済み内容を削除',
  'asmr_download_no_tasks': 'ダウンロードタスクはありません',
  'asmr_download_waiting': '待機中',
  'asmr_download_status': '状態',
  'asmr_download_destination': '保存先',
  'asmr_download_progress': '進捗',
  'asmr_download_skipped': 'スキップ済み',
  'asmr_download_failed_count': '失敗',
  'asmr_download_downloaded': 'ダウンロード済み',
  'asmr_download_total_size': '合計サイズ',
  'asmr_download_cancelled_and_cleared': 'ダウンロードをキャンセルし、取得済み内容を削除しました',
  'asmr_download_summary_selected': '{count} 個のファイルを選択中、合計 {size}',
  'asmr_download_empty_folder': '空のフォルダ',
  'asmr_download_status_preparing': '準備中',
  'asmr_download_status_downloading': 'ダウンロード中',
  'asmr_download_status_paused': '一時停止',
  'asmr_download_status_completed': '完了',
  'asmr_download_status_failed': '失敗',
  'asmr_download_status_idle': '空き',
  'choose_music_folder': '音楽フォルダを選択',
  'import_done_added': '追加完了：{count} 曲を追加しました。',
  'choose_audio_files': '音声ファイルを選択',
  'library_folder_exists': '重複したフォルダがすでに存在します。',
  'library_exists': '重複したライブラリがすでに存在します。',
  'library_file_exists': '重複したファイルがすでに存在します。',
  'imported_files': '追加済みファイル',
  'manually_selected_files': '手動選択ファイル',
  'file_added': 'ファイル追加',
  'library_category_all': 'すべて',
  'library_category_tags': 'タグ',
  'library_category_voice_actors': '声優',
  'library_category_circles': 'サークル',
  'library_category_no_tags': 'タグ情報がありません',
  'library_category_no_voice_actors': '声優情報がありません',
  'library_category_no_circles': 'サークル情報がありません',
  'library_category_no_matches': '一致する音声がありません',
  'copied_to_clipboard': 'コピーしました：{value}',
  'remove_folder': 'フォルダを削除',
  'remove_folder_confirm': 'このフォルダと配下の音声をライブラリから削除しますか？\n\n{name}',
  'cancel': 'キャンセル',
  'remove': '削除',
  'removed_prefix': '削除済み：{name}',
  'session_created': 'セッション作成：{name}',
  'items_count': '{count} 項目',
  'play_first': '先頭を再生',
  'remove_audio_folder': 'フォルダを削除',
  'play': '再生',
  'create_another_session': 'もう1つ作成',
  'remove_audio': '音声を削除',
  'audio_detail': '詳細情報',
  'audio_detail_title': '音声詳細情報',
  'audio_detail_library_root': 'ライブラリのルートフォルダ',
  'audio_detail_single_file': '単独追加音声',
  'audio_detail_cover_image': 'カバー画像',
  'audio_detail_folder_name': 'フォルダ名',
  'audio_detail_file_name': 'ファイル名',
  'audio_detail_rj_code': 'RJ番号',
  'audio_detail_work_title': '作品タイトル',
  'audio_detail_circle_name': 'サークル名',
  'audio_detail_voice_actors': '声優名',
  'audio_detail_tags': 'タグ',
  'audio_detail_release_date': '発売日',
  'audio_detail_sales_count': '販売数',
  'audio_detail_rating': '評価',
  'audio_detail_empty': '未入力',
  'audio_detail_edit_title': '{name}を編集',
  'audio_detail_multi_hint': '複数項目は中国語の読点「，」で区切ってください',
  'audio_detail_backup_failed': 'データベースに保存しましたが、ローカルバックアップに失敗しました。',
  'audio_detail_cover_portability_skipped':
      'カバーが 8 MiB を超えているため、端末上のパスのみ保持し、ポータブルバックアップには保存しませんでした。',
  'audio_detail_restored_from_backup': 'ローカルバックアップから復元しました。',
  'audio_detail_rj_format_hint': 'RJ番号は RJ + 数字の形式を推奨します。',
  'audio_detail_save_failed': '保存に失敗しました。もう一度お試しください。',
  'audio_detail_load_failed': '読み込みに失敗しました。もう一度お試しください。',
  'audio_detail_fetch_info': '情報を取得',
  'audio_detail_fetch_scope_title': '取得範囲を選択',
  'audio_detail_fetch_scope_hint':
      'ASMR.ONE を優先して作品情報を取得し、失敗した場合は DLsite を使用します。書き込む範囲を選択してください。',
  'audio_detail_fetch_scope_all_hint': '取得した情報で現在の詳細情報を上書きします。',
  'audio_detail_fetch_scope_missing_hint': '空欄の詳細情報のみ入力し、既存の内容は保持します。',
  'metadata_scope_missing': '不足データ',
  'audio_detail_fetch_missing_query': 'RJ番号、フォルダ/ファイル名、または作品タイトルを入力してください。',
  'audio_detail_cover_swipe_hint': '左右にスワイプして切り替え',
  'audio_detail_set_cover': 'カバーに設定',
  'audio_detail_current_cover': '現在のカバー',
  'audio_detail_rename_file': 'ファイル名を変更',
  'audio_detail_rename_file_from_title': '作品タイトルを\nファイル名にする',
  'audio_detail_rename_folder_from_title': '作品タイトルを\nフォルダ名にする',
  'audio_detail_rename_confirm':
      '作品タイトルを使って現在のファイルまたはフォルダ名を変更します。ローカルパスが移動されます。続行しますか？',
  'audio_detail_rename_missing_title': '先に作品タイトルを入力してください。',
  'audio_detail_rename_done': '名前を変更しました。',
  'audio_detail_rename_failed': '名前の変更に失敗しました。ファイルの存在や使用状態を確認してください。',
  'dlsite_review_title': '作品データを確認',
  'dlsite_save_cover': 'カバーをフォルダに保存',
  'dlsite_fetch_failed':
      '作品データを取得できませんでした。RJ番号、フォルダ/ファイル名、作品タイトル、またはネットワークを確認してください。',
  'dlsite_cover_save_failed': '情報は保存しましたが、カバーの保存に失敗しました。',
  'confirm': '確認',
  'retry': '再試行',
  'previous': '前へ',
  'next': '次へ',
  'clear_all_sessions': '全セッションをクリア',
  'stop_remove_all_sessions': '実行中の再生セッションをすべて停止して削除しますか？',
  'clear': 'クリア',
  'all_sessions_cleared': '全セッションをクリアしました。',
  'audio_removed': '音声を削除しました。',
  'audio_excluded': 'ライブラリから音声を除外しました。',
  'folder_removed': 'フォルダを削除しました。',
  'folder_excluded': 'ライブラリからフォルダを除外しました。',
  'pause_all_sessions': '全セッションを一時停止',
  'all_paused': '全セッションを一時停止しました。',
  'sessions_count': '{count} セッション',
  'playing_count': '再生中 {count}',
  'no_active_sessions': 'アクティブなセッションはありません',
  'go_library_hint': '先にライブラリで音声を再生してから、並行セッションを作成してください。',
  'single_loop': '1曲リピート',
  'cross_folder': 'フォルダ横断',
  'current_folder': '現在のフォルダ',
  'random_order': 'ランダム',
  'sequential_order': '順番',
  'no_other_audio_in_folder': 'このフォルダには切り替え可能な他の音声がありません。',
  'switch_audio': '音声を切替',
  'channel_swap': '左右チャンネル入れ替え',
  'channel_swap_desc': '左右の音声を入れ替えます。',
  'skip_silence': '無音スキップ',
  'skip_silence_desc': '無音部分を短縮します。',
  'noise_reduction': 'ノイズ低減',
  'noise_reduction_desc': '鋭いノイズを軽減します。',
  'volume_normalization': '音量ノーマライズ',
  'volume_normalization_desc': '突発的な音量を抑え均一化します。',
  'audio_features': '機能',
  'equalizer': 'イコライザー',
  'time_segments': '時間区間',
  'equalizer_supported': 'この端末の対応バンドで調整します。',
  'equalizer_enable_hint': 'オンにすると端末の対応バンドを読み込みます。',
  'equalizer_unavailable': 'EQ バンドをまだ取得できません。オンにして少し待ってください。',
  'eq_preset': 'プリセット',
  'eq_reset': 'リセット',
  'eq_save_preset': 'プリセット保存',
  'eq_preset_name': 'プリセット名',
  'eq_preset_flat': 'フラット',
  'eq_preset_asmr_immersive': 'ASMR没入',
  'eq_preset_voice_clear': '声を明瞭に',
  'eq_preset_ear_massage': '耳かき・マッサージ',
  'eq_preset_night_soft': '夜間ソフト',
  'eq_preset_bass_boost': '低音強調',
  'previous_track': '前の曲',
  'pause': '一時停止',
  'resume': '再開',
  'next_track': '次へ',
  'collapse': '折りたたむ',
  'expand': '展開',
  'end_session': 'セッション終了',
  'random_play': 'ランダム再生',
  'sequential_play': '順番再生',
  'cross_folder_play': 'フォルダ横断再生',
  'current_folder_only': '現在フォルダのみ',
  'dark_mode': 'テーマカラー',
  'dark_mode_subtitle': 'アプリの外観を選択します。',
  'cover_image_resolution': 'カバー画像の表示解像度',
  'cover_image_resolution_subtitle': 'カバー画像の最大表示サイズを設定します。',
  'cover_image_resolution_300': '省メモリ 300px',
  'cover_image_resolution_600': 'バランス 600px',
  'cover_image_resolution_900': '高画質 900px',
  'cover_image_resolution_original': '元画像',
  'theme_system': 'システム',
  'theme_light': 'ライト',
  'theme_dark': 'ダーク',
  'differentiate_asmr_theme': 'ASMR.ONE ページを区別する',
  'differentiate_asmr_theme_subtitle': '有効にすると、ASMR.ONE 関連ページで専用のテーマカラーを使用します',
  'bottom_navigation_style': 'フローティングメニューバー',
  'bottom_navigation_style_subtitle': 'カプセル状の外観を有効にします。',
  'blur_player_background': 'プレーヤーの背景をぼかす',
  'blur_player_background_subtitle': '再生画面の背景をぼかします。',
  'ui_blur_effect': 'UI ぼかし効果',
  'ui_blur_effect_subtitle': 'UIのぼかし効果を有効にします。',
  'multi_thread_playback': 'マルチスレッド再生',
  'multi_thread_playback_subtitle': '複数の音声を同時に再生します。',
  'notification_bar': '再生通知コントロール',
  'notification_bar_subtitle': '再生通知の表示を制御します。',
  'show_playback_card': '再生カード表示',
  'show_playback_card_subtitle': '画面下部に再生カードを表示します。',
  'section_detail_info': '詳細情報',
  'card_info_display': 'カード表示情報',
  'card_info_display_subtitle': '{count} / {max} 項目を選択中',
  'card_info_none': '詳細情報を表示しない',
  'card_info_release_date': '発売',
  'card_info_sales_count': '販売数',
  'card_info_rating': '評価',
  'card_info_duration': '時間',
  'auto_play_added_sessions': '追加後すぐに再生',
  'auto_play_added_sessions_subtitle': '音声追加時にすぐ再生を開始します。',
  'asmr_playback_cache': 'ASMR.ONE再生後キャッシュ',
  'asmr_playback_cache_subtitle': '再生済み音声をキャッシュし、再読み込みを減らします。',
  'record_playback_progress': '前回の再生位置を記録する',
  'record_playback_progress_subtitle': 'アプリ起動時に再生進捗を復元します。',
  'section_general': '基本',
  'section_appearance': '外観',
  'section_playback': '再生',
  'section_asmr_download': 'ASMR.ONEダウンロード',
  'asmr_download_path_setting': 'ダウンロード先',
  'asmr_download_path_not_set': '未設定',
  'asmr_download_conflict_setting': '同名ファイルの処理',
  'asmr_download_conflict_setting_subtitle': '同名のファイルやフォルダがある場合の処理方法を選びます。',
  'section_data_storage': 'データとストレージ',
  'section_system_updates': 'システムと更新',
  'permission_center': '権限とバックグラウンド実行',
  'permission_center_subtitle': 'オプション権限を確認・管理します。',
  'permission_state_authorized': '許可済み',
  'permission_state_unauthorized': '未許可',
  'permission_state_restricted': '制限あり',
  'permission_state_recommended': '推奨',
  'permission_enabled': '有効',
  'permission_not_enabled': '未設定',
  'system_settings_open_failed': 'システム設定を開けませんでした。アプリ設定から手動で変更してください。',
  'permission_notification_description': 'バックグラウンド再生状態とメディア操作を表示します。',
  'permission_background_description': '画面オフ時に一部端末が再生を制限する可能性を減らします。',
  'permission_exact_alarm_description': 'スリープタイマーの自動再開の信頼性を高めます。',
  'permission_manage_files_description':
      'ファイルシステムを直接走査する高度な曲庫スキャンでのみ必要です。通常はシステムのフォルダ選択を推奨します。',
  'permission_overlay_description': '他のアプリ上にグローバル字幕を表示する場合のみ必要です。',
  'permission_update_install_description':
      'ユーザーが明示的にダウンロードした GitHub Release 更新のインストールにのみ使用します。',
  'data_and_support': 'データとサポート',
  'data_and_support_subtitle': 'バックアップと診断レポートの管理。',
  'export_backup': 'バックアップを出力',
  'export_backup_subtitle': 'データベースと設定を出力します。',
  'restore_backup': 'バックアップを復元',
  'restore_backup_subtitle': 'データベースと設定を復元します。',
  'restore_backup_confirm':
      '復元すると現在の曲庫データベースと移行可能な設定が置き換わります。失敗時は自動的に元に戻します。続行しますか？',
  'operation_completed': '完了',
  'operation_failed': '操作に失敗しました',
  'backup_exported': 'バックアップを出力しました。',
  'backup_invalid': 'バックアップが無効、破損、または未対応です。',
  'backup_invalid_next_step': '別のバックアップを選択してください。問題が続く場合は診断レポートを出力してください。',
  'backup_restored_restart': 'バックアップを復元し、データを読み込みました。',
  'backup_restored_loaded': '復元したデータベースと設定を読み込みました。',
  'export_diagnostics': '診断レポートを出力',
  'unexpected_error_title': 'Nameless Audio で予期しないエラーが発生しました',
  'unexpected_error_message':
      'ローカルデータは保持されています。診断レポートを出力してから、アプリを閉じて再起動してください。',
  'close_and_restart': '閉じて再起動',
  'export_diagnostics_subtitle': '診断レポートを出力します。',
  'diagnostics_exported': '診断レポートを出力しました。',
  'operation_failed_retry': '操作に失敗しました。もう一度お試しください。',
  'operation_failed_diagnostics_hint': 'もう一度お試しください。問題が続く場合は診断レポートを出力してください。',
  'section_danger_zone': 'その他',
  'allow_background_run': 'バックグラウンド実行を許可',
  'allow_background_run_subtitle': 'バックグラウンド制限を防ぎます。',
  'allow_background_run_ready': 'このアプリのバックグラウンド実行は許可されています。画面オフ再生がより安定します。',
  'allow_background_run_checking': 'バックグラウンド実行の状態を確認しています...',
  'allow_background_run_open_failed': 'システム設定を開けませんでした。アプリ設定から手動で変更してください。',
  'notification_permission_status': '通知権限の状態',
  'notification_permission_ready': '通知権限は有効です。バックグラウンド操作を表示でき、画面オフ再生がより安定します。',
  'notification_permission_missing':
      '通知権限が無効です。システムがバックグラウンド再生通知や操作表示を制限する場合があります。',
  'notification_permission_checking': '通知権限を確認しています...',
  'notification_settings_open_failed': '通知設定を開けませんでした。システム設定から手動で変更してください。',
  'open_notification_settings': '通知設定を開く',
  'exact_alarm_permission_status': '正確なアラームの状態',
  'exact_alarm_permission_ready': '正確なアラームは利用可能です。長時間バックグラウンド後の自動再開がより安定します。',
  'exact_alarm_permission_missing':
      '正確なアラームが無効です。長時間バックグラウンド後の自動再開が不安定になる場合があります。',
  'exact_alarm_permission_checking': '正確なアラームの状態を確認しています...',
  'exact_alarm_settings_open_failed': '正確なアラーム設定を開けませんでした。システム設定から手動で変更してください。',
  'clear_app_cache': 'アプリキャッシュを削除',
  'clear_app_cache_subtitle': 'カバーや一時ファイルを削除します。',
  'clear_app_cache_confirm':
      'このアプリが作成したキャッシュを削除します。ライブラリの元ファイルは削除されません。続行しますか？',
  'app_cache_cleaned': '{size} のキャッシュを削除しました。',
  'app_cache_none': '削除できるアプリキャッシュはありません。',
  'max_cache_size': '最大キャッシュ容量',
  'max_cache_size_subtitle': '上限: {size}。古いキャッシュを自動削除します。',
  'check': '確認',
  'check_updates': '更新を確認',
  'check_updates_subtitle': 'GitHub でアップデートを確認します。',
  'auto_check_updates': '更新を自動確認',
  'auto_check_updates_subtitle': 'アプリ起動時に自動でアップデートを確認します。',
  'check_updates_subtitle_latest': '現在は最新バージョンです：{version}',
  'checking_updates': 'GitHub の最新バージョンを確認しています...',
  'latest_version_available': '新しいバージョンがあります',
  'open_release_page': 'リリースページを開く',
  'current_version_label': '現在のバージョン：{version}',
  'latest_version_label': '最新バージョン：{version}',
  'update_available_subtitle': '更新可能なバージョン：{version}',
  'download_update': '更新をダウンロード',
  'downloading_update': '更新をダウンロード中：{percent}%',
  'no_updates_available': '現在は最新バージョンです。',
  'update_no_compatible_release': '現在利用できる互換性のある安定版はありません。',
  'update_missing_asset': '最新バージョンにこのプラットフォーム用のインストーラーがありません。',
  'update_missing_checksum': '最新バージョンに SHA-256 チェックサムファイルがありません。',
  'update_check_failed': '更新確認に失敗しました。後でもう一度お試しください。',
  'update_check_failed_next_step':
      'ネットワーク接続または GitHub へのアクセス状態を確認してから、もう一度お試しください。',
  'update_download_failed': '更新のダウンロードに失敗しました。ネットワークを確認してください。',
  'update_download_failed_next_step':
      'ダウンロードまたは SHA-256 検証が完了しませんでした。再試行するか、GitHub Release ページを開いて手動でダウンロードしてください。',
  'update_install_preparing_title': '更新を準備しています',
  'update_install_preparing_message':
      'バージョン {version} をダウンロードし、SHA-256 検証を完了しました。更新を完了するため、アプリが自動で終了して再起動する場合があります。ファイル: {path}',
  'update_ready_install': 'インストーラーを開きました。画面の指示に従って更新してください。',
  'update_windows_ready_install': '更新プログラムの準備ができました。アプリを終了して再起動し、更新を完了します。',
  'update_install_failed': '更新のインストールを続行できませんでした。',
  'update_install_failed_next_step':
      '後でもう一度お試しください。まだ失敗する場合は更新ログを確認するか、GitHub Release ページから手動でインストールしてください。',
  'update_install_failed_with_detail':
      '後でもう一度お試しください。まだ失敗する場合は更新ログを確認してください。詳細: {detail}',
  'open_update_log': 'ログを表示',
  'install_permission_needed': 'このアプリから不明なアプリをインストールする許可を有効にしてください。',
  'install_permission_title': 'アップデートのインストールを許可',
  'install_permission_message':
      '新しいバージョンのダウンロードとインストールを続けるには、このアプリから不明なアプリをインストールする許可が必要です。今すぐ設定を開きますか？',
  'transcode_defaults': '変換の既定値',
  'format': '形式',
  'bitrate': 'ビットレート',
  'bitrate_used': 'MP3 / AAC / OGG 出力でこのビットレートを使用します。',
  'bitrate_not_used': '{format} は形式内蔵のエンコードを使うため、ビットレート設定は無効です。',
  'about': '情報',
  'app_desc': '並行セッションと高音質再生に対応。',
  'language': '言語',
  'language_subtitle': '表示言語を切り替え',
  'startup_page': 'アプリ起動時のページ',
  'startup_page_subtitle': 'アプリ起動時のデフォルトページ。',
  'startup_page_asmrOne': 'ASMR.ONE',
  'startup_page_library': 'ライブラリ',
  'startup_page_playlist': 'プレイリスト',
  'haptic_feedback_enabled': 'バイブレーション',
  'haptic_feedback_enabled_subtitle': 'インタラクション時にバイブレーションを提供する。',
  'dlsite_metadata_language': 'DLsiteデータ取得言語',
  'dlsite_metadata_language_subtitle': 'DLsite 情報取得の言語。既定ではページ言語に従います。',
  'timer_title': 'タイマー',
  'set_countdown': 'カウントダウン設定',
  'start_mode': '開始方法',
  'confirm_start_now': '確定してすぐ開始',
  'confirm_wait_playback': '確定して再生開始を待つ',
  'set_duration_first': '先にカウントダウン時間を設定してください。',
  'cancel_timer': 'タイマー解除',
  'auto_resume_after_timer': '定時再開',
  'auto_resume_subtitle': '指定時刻に再生を自動再開します。',
  'resume_time': '再開時刻：{time}',
  'tap_choose_resume_time': 'タップして自動再開時刻を選択',
  'choose_auto_resume_time': '自動再開時刻を選択',
  'set_timer_to_enable_auto_resume': 'タイマーを設定すると、ここで自動再開機能を有効化できます。',
  'wait_play_trigger': '再生トリガー待機',
  'manual_start': 'すぐに開始',
  'auto_start_after_play': '音声再生後に自動開始',
  'countdown_finished': 'カウントダウン終了',
  'waiting_to_start_countdown': '再生開始後にカウント開始',
  'counting_down': 'カウントダウン中',
  'waiting_for_auto_resume': '自動再開を待機中',
  'paused_audio_count': '{count} 件の音声を一時停止しました',
  'auto_resume_at': '{time} に自動再開します',
  'hour': '時',
  'minute': '分',
  'second': '秒',
  'manual_start_subtitle': 'すぐにカウントダウンを開始します。',
  'trigger_start_subtitle': '再生検出時にカウントダウンを開始します。',
  'selected_file': '選択済み：{name}',
  'select_video_and_output': '先に動画ファイルと出力先を選択してください。',
  'conversion_starting': '変換を開始...',
  'converting_percent': '変換中：{percent}%',
  'conversion_done_saved': '変換完了、保存先：{path}',
  'conversion_canceled': '変換をキャンセルしました。',
  'conversion_failed': '変換に失敗しました。再試行してください。',
  'canceling_conversion': '変換をキャンセル中...',
  'source_video_file': '動画ファイル',
  'tap_select_video_file': '変換する動画ファイルを選択',
  'output_directory': '出力先',
  'tap_select_output_dir': '音声の保存先を選択',
  'current_params': '現在の設定：{value}',
  'format_auto_encode': '形式自動エンコード',
  'cancel_conversion': '変換をキャンセル',
  'notification_permission_title': '通知権限を有効化',
  'notification_permission_message':
      'このアプリの通知がシステムで無効になっているため、再生通知は表示されません。アプリ通知とメディア通知を有効にしてください。',
  'notification_permission_enabled': '通知権限が有効になりました。',
  'background_play_permission_title': 'バックグラウンド再生を許可',
  'background_cleaner_detected_title': 'バックグラウンド再生が強制停止されました',
  'background_cleaner_detected_message':
      '強制停止後はアプリを自動再起動できません。vivo の設定でバックグラウンドの高電力使用と自動起動を許可してください。',
  'background_play_permission_message':
      '画面オフ後も音声を再生し続けるために、アプリを電池制限の対象外に設定してください。設定画面を開きますか？',
  'manage_files_permission_title': 'すべてのファイルへのアクセスを許可',
  'manage_files_permission_message':
      'このアプリにはまだ「すべてのファイルの管理」権限がありません。フォルダや曲庫の取り込み、ローカル資源の読み取りに失敗する可能性があります。今すぐ設定を開きますか？',
  'manage_files_permission_enabled': 'すべてのファイルへのアクセスを許可しました。',
  'go_settings': '設定を開く',
  'later': 'あとで',
  'start_conversion': '変換開始',
  'choose_library': '曲庫を追加',
  'choose_library_folder': '曲庫フォルダを選択',
  'import_library_done':
      '曲庫の取り込みが完了しました。{folderCount} 個のルートフォルダと {count} 曲を追加しました。',
  'no_child_folder_found': '選択したフォルダの直下に取り込める子フォルダがありません。',
  'edit_library': 'ライブラリ編集',
  'edit_library_hint': '追加済みライブラリ、フォルダ、音声を管理します',
  'library_removed': 'ライブラリを削除しました。',
  'remove_library': 'ライブラリを削除',
  'remove_library_confirm': 'このライブラリと追加済みフォルダを削除しますか？\n\n{name}',
  'excluded': '除外済み',
  'restore': '復元',
  'exclude': '除外',
  'library_edit_empty': '追加済みライブラリはありません。',
  'subtitle_window_settings': '字幕フローティングウィンドウ',
  'subtitle_window_settings_subtitle': 'フォント、色、背景を調整します。',
  'subtitle_window_preview': 'ライブプレビュー',
  'subtitle_window_preview_hint': '下の設定をスクロールしても、ここは固定されたまま同期更新されます。',
  'subtitle_preview_sample': '波の音がゆっくり近づき、呼吸も少しずつ落ち着いていきます。',
  'font_setting': 'フォント設定',
  'system_default': 'システムデフォルト',
  'font_color': 'フォント色',
  'background_opacity': '背景透明度',
  'background_transparency': '背景透明度',
  'background_color': '背景色',
  'reset_to_default': 'デフォルトにリセット',
  'restore_default': 'デフォルトに戻す',
  'turn_on_subtitle': '字幕を表示',
  'turn_off_subtitle': '字幕を非表示',
  'subtitle_global_display': '字幕グローバル表示',
  'overlay_permission_title': '字幕用オーバーレイを許可',
  'overlay_permission_message':
      '字幕のグローバル表示を有効にするには、このアプリにオーバーレイ表示を許可する必要があります。これにより、他のページやバックグラウンドでも字幕を表示し続けられます。今すぐ設定を開きますか？',
  'border_depth': '枠線の深さ',
  'font_size': 'フォントサイズ',
  'volume': '音量',
  'volume_range_hint': '0-200',
  'playback_speed': '再生速度',
  'volume_balance': 'L/R バランス',
  'speed_reset': '1.0x に戻す',
  'segment_add': '区間ラベルを追加',
  'segment_start': '開始',
  'segment_end': '終了',
  'segment_name': 'ラベル名',
  'segment_name_hint': 'ラベル名を入力',
  'segment_time_input_title': '時刻を入力',
  'segment_delete_title': '区間ラベルを削除',
  'segment_delete_confirm': '「{name}」を削除しますか？',
  'segment_loop': '区間リピート',
  'volume_warning_title': '音量警告',
  'volume_warning_message': '音量ブーストはクリッピングや歪みの原因になることがあります',
  'exact_alarm_permission_title': '正確なアラームを許可',
  'exact_alarm_permission_message':
      '画面オフ・バックグラウンド・長時間後の自動再開を安定させるため、このアプリに正確なアラームを許可することをおすすめします。',
  'open_exact_alarm_settings': '正確なアラーム設定を開く',
  'timer_reliability_checking': 'タイマーのバックグラウンド信頼性を確認しています...',
  'timer_reliability_ready': 'バックグラウンド再開の条件は満たされています',
  'timer_reliability_missing': '安定性を高めるため、通知とバックグラウンド関連の権限を確認してください',
  'add_playback_queue': '再生キューを追加',
  'default_playback_queue_name': '再生キュー {number}',
  'edit_playback_queue': '再生キューを編集',
  'edit_queue_audio': 'キューの音声を編集',
  'edit_queue_name': 'キュー名を編集',
  'edit_card_color': 'カード色を編集',
  'remove_queue': 'キューを削除',
  'remove_queue_confirm': 'この再生キューを削除しますか？',
  'queue_added_audio': 'キューに追加済み',
  'playback_list_audio': '再生リストの音声',
  'add_audio_to_queue': '音声をキューに追加',
  'add_work_to_queue': '作品をキューに追加',
  'empty_playback_queue': 'キューに音声がありません',
  'queue_add_audio_first': '先に音声をキューへ追加してください',
  'edit': '編集',
  'save': '保存',
};
